version: 0.2
phases:
  build:
    commands:
      - echo "building"
      - echo "Linux-application" > app
      - echo '''version: 0.0 \nos: linux \nfiles: \n\t- source: / \n\t\tdestination: /home/ec2-user/deployment-dir''' > appspec.yml

artifacts:
  type: zip
  files:
    - app
    - appspec.yml
